# Generated by Django 6.0.3 on 2026-03-31 01:16

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default=games.models.get_default_game_name, max_length=200),
        ),
    ]
