# Generated by Django 6.0.3 on 2026-03-31 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_default_game_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='score',
            name='game_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.gameplayer'),
        ),
        migrations.CreateModel(
            name='GuestPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_players', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='guest_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.guestplayer'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('game_player__isnull', False), ('guest_player__isnull', False), _connector='XOR'), name='score_belongs_to_one_player_type'),
        ),
        migrations.AlterUniqueTogether(
            name='guestplayer',
            unique_together={('game', 'name')},
        ),
    ]
